name: Release

on:
  workflow_dispatch:


env:
  GO_VERSION: 1.17
  CGO_ENABLED: 0
  GO111MODULE: on

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ linux, windows, darwin ]
        arch: [ amd64, arm64, 386 ]
        include:
          - os: windows
            file-extension: ".exe"
        exclude:
          - os: darwin
            arch: 386
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
      FILEEXTENSION: ${{ matrix.file-extension }}
      FILENAME: m3u8-downloader-${GOOS}-${GOARCH}${FILEEXTENSION}
    steps:
    - name: Checkout Git repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Get dependencies
      run: |
        go mod download

    - name: Build binary
      run: |
        GOOS=${GOOS} GOARCH=${GOARCH} go build  -o ./Releases/${FILENAME} m3u8-downloader.go

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.FILENAME }}
        path: ./Releases/*

        
